### ISSUE TITLE
[bug/enhancement] Import time

### ISSUE THREAD

**Issue by rwijtvliet** [rwijtvliet/portfolyo#73]
The statement `import portfolyo`takes several seconds, compared to near instantaneous for other packages, including large ones. It seems some expensive code is executed, either in the package itself or in one of its dependencies. 

Maybe we can improve this, maybe with the help of a profiler (cProfile e.g)

**Comment by Pizza2Pizza** [comment]
I'm not sure what the problem is. I rung this code: 
import cProfile
import portfolyo as pf
def main():
    import portfolyo as pf

if __name__ == "__main__":
    cProfile.run("main()", sort="cumulative")


and my results are zeros everywhere. Can you run it on your end and tell me the results?

**Comment by rwijtvliet** [comment]
If a package is imported once, it's skipped on subsequent imports. Try (from memory, so check) `from importlib import releoad` and then in `main`: `pf = import portfolyo as pf`

**Comment by rwijtvliet** [comment]
Let's close this issue for now and focus on other priorities
